name: Run Job Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

env:
  AWS_REGION: 'us-east-1'
  API_ENDPOINT: 'https://dnmh5xqaek.execute-api.us-east-1.amazonaws.com/prod'
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PW: ${{ secrets.TEST_USER_PW }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  QUEUE_TIMEOUT_MAX: 90
  QUEUE_TIMEOUT_WARNING: 30
  LOG_LEVEL: 'info'
  WAIT_SECONDS: 1

jobs:
  run-job-monitor:
    runs-on: ubuntu-latest
    outputs:
      error-message: ${{ steps.set-error-message.outputs.ERROR_MESSAGE }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Run job monitor
      run: |
        npm install
        npm start 2>&1 | tee output.log
    - name: Set error message
      id: set-error-message
      if: ${{ failure() }}
      run: echo "ERROR_MESSAGE=$(cat output.log | grep 'Error:')" >> "$GITHUB_OUTPUT"
  notify-on-failure:
    needs: run-job-monitor
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
    - name: Notify on failure
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        ERROR_MESSAGE: ${{ needs.run-job-monitor.outputs.error-message }}
      uses: Ilshidur/action-discord@master
      with:
        args: '**{{ GITHUB_WORKFLOW }}** workflow on **{{ GITHUB_REPOSITORY }}** failed with: ```{{ ERROR_MESSAGE }}``` [More details]({{ GITHUB_SERVER_URL }}/{{ GITHUB_REPOSITORY }}/actions/runs/{{ GITHUB_RUN_ID }})'