name: Run Job Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

env:
  AWS_REGION: 'us-east-1'
  API_ENDPOINT: 'https://dnmh5xqaek.execute-api.us-east-1.amazonaws.com/prod'
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PW: ${{ secrets.TEST_USER_PW }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  TIMEOUT_SECONDS: 90
  QUEUED_TIMEOUT_SECONDS: 30
  LOG_LEVEL: 'info'
  WAIT_SECONDS: 1

jobs:
  run-job-monitor:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Run job monitor
      run: |
        npm install
        npm start
  # debug:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Print
  #       run: env | sort
  # notify-on-failure:
  #   needs: run-job-monitor
  #   runs-on: ubuntu-latest
  #   if: failure()

  #   steps:
  #   - name: Notify on failure
  #     env:
  #       DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #     uses: Ilshidur/action-discord@master
  #     with:
  #       args: 'Job Failed: {{ GITHUB_ACTION }} - {{ GITHUB_REPOSITORY }}'